DROP TABLE IF EXISTS trades CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS circuit_breakers CASCADE;
DROP TABLE IF EXISTS circuit_breaker_activations CASCADE;
DROP TABLE IF EXISTS equity_tracking CASCADE;
DROP TABLE IF EXISTS rejected_signals CASCADE;
DROP TABLE IF EXISTS system_metrics CASCADE;
